--- #YAML:1.0
name:                DTS
version:             0.05
abstract:            Perl classes to access Microsoft SQL Server 2000 DTS Packages 
license:             ~
author:              
    - Alceu Rodrigues de Freitas Junior <arfreitas@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.4401
distribution_type:   module
requires:     
    Carp:                          1.04
    Class::Accessor:               0.25
    Class::Publisher:              0.2
    DateTime:                      0.35
    Devel::AssertOS:               0
    Hash::Util:                    0.05
    Win32::OLE:                    0.1704
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
